# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_mult_cpp <- function(m1, m2) {
    .Call('_MpoxModelPack_matrix_mult_cpp', PACKAGE = 'MpoxModelPack', m1, m2)
}

matrix_round_cpp <- function(mat) {
    .Call('_MpoxModelPack_matrix_round_cpp', PACKAGE = 'MpoxModelPack', mat)
}

matrix_exp_cpp <- function(m1) {
    .Call('_MpoxModelPack_matrix_exp_cpp', PACKAGE = 'MpoxModelPack', m1)
}

outer_cpp <- function(x, y) {
    .Call('_MpoxModelPack_outer_cpp', PACKAGE = 'MpoxModelPack', x, y)
}

ipf_cpp <- function(M, m1, m2, tol = 1e-12) {
    .Call('_MpoxModelPack_ipf_cpp', PACKAGE = 'MpoxModelPack', M, m1, m2, tol)
}

apply_mix_odds_cpp <- function(M0, OR, tol = 1e-12) {
    .Call('_MpoxModelPack_apply_mix_odds_cpp', PACKAGE = 'MpoxModelPack', M0, OR, tol)
}

fn_model_cpp <- function(bbeta_city, omega_city, RR_H_city, RR_L_city, gamma1_city, TRACING = 1L, VACCINATING = 1L) {
    .Call('_MpoxModelPack_fn_model_cpp', PACKAGE = 'MpoxModelPack', bbeta_city, omega_city, RR_H_city, RR_L_city, gamma1_city, TRACING, VACCINATING)
}

