# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fn_model_cpp <- function(bbeta_city, omega_city, RR_H_city, RR_L_city, gamma1_city, TRACING = 1L, VACCINATING = 1L) {
    .Call('_MpoxModelPack_fn_model_cpp', PACKAGE = 'MpoxModelPack', bbeta_city, omega_city, RR_H_city, RR_L_city, gamma1_city, TRACING, VACCINATING)
}

