// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fn_model_cpp
Rcpp::List fn_model_cpp(double bbeta_city, double omega_city, double RR_H_city, double RR_L_city, double gamma1_city, bool TRACING, bool VACCINATING);
RcppExport SEXP _MpoxModelPack_fn_model_cpp(SEXP bbeta_citySEXP, SEXP omega_citySEXP, SEXP RR_H_citySEXP, SEXP RR_L_citySEXP, SEXP gamma1_citySEXP, SEXP TRACINGSEXP, SEXP VACCINATINGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type bbeta_city(bbeta_citySEXP);
    Rcpp::traits::input_parameter< double >::type omega_city(omega_citySEXP);
    Rcpp::traits::input_parameter< double >::type RR_H_city(RR_H_citySEXP);
    Rcpp::traits::input_parameter< double >::type RR_L_city(RR_L_citySEXP);
    Rcpp::traits::input_parameter< double >::type gamma1_city(gamma1_citySEXP);
    Rcpp::traits::input_parameter< bool >::type TRACING(TRACINGSEXP);
    Rcpp::traits::input_parameter< bool >::type VACCINATING(VACCINATINGSEXP);
    rcpp_result_gen = Rcpp::wrap(fn_model_cpp(bbeta_city, omega_city, RR_H_city, RR_L_city, gamma1_city, TRACING, VACCINATING));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MpoxModelPack_fn_model_cpp", (DL_FUNC) &_MpoxModelPack_fn_model_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MpoxModelPack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
